### ISSUE TITLE
手机号登录报错

### ISSUE THREAD

**Issue by renyancheng** [Flysky12138/vuetify-cloudmusic#2]
当我在登录页面使用手机号+密码登录时，控制台出现了报错QAQ
> Failed to load resource: the server responded with a status of 404 () 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'code')

**Comment by Flysky12138** [comment]
这手机号登录我知道一直有问题，接口请求会提示频繁登录。
```
{
  "msg": "操作频繁，请稍候再试",
  "code": 406,
  "message": "操作频繁，请稍候再试"
}
```
- 按照[#1376](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1376)的方法改`/util/request.js`可以解决。
- 我登录不了就是换扫码登录。

但是你这提示 `404`，你应该不是本地运行的接口吧，还是建议本地运行接口。若是本地接口，试试访问
`http://localhost:3000/login/cellphone?phone=手机号&password=密码`
看得到的结果是什么，自己的信息不要也发出来了哈。
